routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('announcements');
})->name('announcements');

Route::get('login', ['as' => 'guest.login', 'uses' => 'AuthController@login']);
Route::post('login', ['as' => 'guest.login', 'uses' => 'AuthController@authenticate']);

Route::get('register', ['as' => 'guest.register', 'uses' => 'AccountController@create']);
Route::post('register', ['as' => 'guest.register', 'uses' => 'AccountController@store']);

Route::get('order/notification', ['as' => 'order.notification', 'uses' => 'OrderController@notification']);

Route::group(['middleware' => ['auth']], function () {
    Route::any('logout', ['as' => 'auth.logout', 'uses' => 'AuthController@logout']);
    Route::get('vote/{site}', ['as' => 'vote.site', 'uses' => 'VoteController@redirect']);

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('/', ['as' => 'index', 'uses' => 'OrderController@order']);
        Route::post('/', ['as' => 'index', 'uses' => 'OrderController@postOrder']);
        Route::get('history', ['as' => 'history', 'uses' => 'OrderController@history']);
        Route::get('status', ['as' => 'status', 'uses' => 'OrderController@status']);
        Route::get('completed/{txn}', ['as' => 'completed', 'uses' => 'OrderController@completed']);
        Route::get('canceled/{order}', ['as' => 'canceled', 'uses' => 'OrderController@canceled']);
    });
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'account_id',
        'package_id',
        'transaction_id',
        'total',
        'status',
    ];

    protected $perPage = 15;

    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    public function package()
    {
        return $this->belongsTo(Package::class);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderRequest;
use App\Models\Order;
use App\Models\Package;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

define('PAYPAL_SANDBOX', 'https://www.sandbox.paypal.com');
define('PAYPAL_SANDBOX_AUTH', 'vuhnqc6jYvI5CsEnxf5VwYHneM9hX_xuLIlFKkWT4fHaMxbhqork6v1UfFK');
define('PAYPAL_PRODUCTION', 'https://www.paypal.com');
define('PAYPAL_PRODUCTION_AUTH', '');

/**
 * Class OrderController
 * @package App\Http\Controllers
 */
class OrderController extends Controller
{
    /** @var string $paypalEnvironment */
    private $paypalEnvironment;

    /** @var string $paypalAuth */
    private $paypalAuth;

    /**
     * OrderController constructor.
     */
    public function __construct()
    {
        $this->paypalEnvironment = PAYPAL_PRODUCTION;
        $this->paypalAuth = PAYPAL_PRODUCTION_AUTH;

        if (env('APP_DEBUG') === true) {
            $this->paypalEnvironment = PAYPAL_SANDBOX;
            $this->paypalAuth = PAYPAL_SANDBOX_AUTH;
        }
    }

    /**
     * @return Factory|View
     */
    public function order()
    {
        $packages = Package::active()->get();

        return view('orders.checkout', compact('packages'));
    }

    /**
     * @param OrderRequest $request
     * @return RedirectResponse
     */
    public function postOrder(OrderRequest $request)
    {
        if (null === $package = Package::find($request->input('package'))) {
            throw new \RuntimeException('Package not found');
        }

        $order = Order::create([
            'status' => 'pending',
            'account_id' => Auth::user()->id,
            'package_id' => $package->id,
            'total' => $package->price,
        ]);

        $params = http_build_query([
            'cmd' => '_donations',
            'business' => 'bjornvisser-facilitator@live.nl',
            'item_name' => $package->name,
            'amount' => $package->price,
            'cancel_return' => route('order.canceled', $order->id),
            'currency_code' => 'USD',
            'item_number' => $order->id,
        ]);

        return Redirect::away($this->paypalEnvironment . '?' . $params);
    }

    /**
     * @param string $txn
     * @return Factory|View
     */
    public function completed($txn)
    {
        $order = Order::where('transaction_id', $txn)->first();

        if (null === $order) {
            throw new \RuntimeException('Order #'. $txn .' not found');
        }

        return view('orders.completed', compact('order'));
    }

    /**
     * @param Request $request
     *
     * @return RedirectResponse
     */
    public function status(Request $request)
    {
        $order = Order::find($request->input('item_number'));

        if (null === $order) {
            throw new \RuntimeException('Order not found');
        }

        $client = new Client([
            'base_uri' => $this->paypalEnvironment,
            'verify' => false,
        ]);

        try {
            $request = $client->post('/cgi-bin/webscr', [
                'form_params' => [
                    'tx' => $request->input('tx'),
                    'at' => $this->paypalAuth,
                    'cmd' => '_notify-synch',
                ],
            ]);
        } catch (RequestException $e) {
            header('Content-type: text/html;');
            print($e->getMessage());
            die();
        }

        $params = [];
        $result = explode("\n", $request->getBody()->getContents());

        if (strtolower($result[0]) === 'success') {
            unset($result[0]);
            foreach ($result as $item) {
                $keyVal = explode('=', $item, 2);

                if (array_key_exists('1', $keyVal)) {
                    $params[urldecode($keyVal[0])] = urldecode($keyVal[1]);
                }
            }

            $order->transaction_id = $params['txn_id'];

            if (strtolower($params['payment_status']) === 'completed') {
                $order->status = strtolower($params['payment_status']);

                $account = $order->account;
                $account->itemmall_points += ($order->package->points + calcBonus($order->package->points, $order->package->bonus_percentage));
                $account->save();
            }

            $order->save();
        }

        return redirect()->route('order.completed', $order->transaction_id);
    }

    /**
     * @return Factory|View
     */
    public function canceled(Order $order)
    {
        $order->status = 'canceled';
        $order->save();

        return redirect()->route('order.index');
    }

    public function history()
    {
        $orders = Auth::user()->orders()->paginate();

        return view('orders.history', compact('orders'));
    }
}

resources/views/orders/checkout.blade.php
@extends('layouts.default')

@section('title', 'Checkout')

@section('content')
    <div class="card">
        <div class="card-header">
            @yield('title')
        </div>
        <form action="{{ route('order.index') }}" method="post">
            {{ csrf_field() }}
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>points</th>
                            <th class="text-right">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($packages as $package)
                        <tr>
                            <td>
                                <label for="package-{{ $package->id }}" class="sr-only">Package {{ $package->id }}</label>
                                <input type="radio" @if((int)$package->price === 10) checked="checked" @endif name="package" id="package-{{ $package->id }}" value="{{ $package->id }}">
                            </td>
                            <td>{{ $package->name }}</td>
                            <td>
                                {{ format($package->points) }}
                                @if($package->bonus_percentage)
                                    <span class="badge badge-success">
                                        +{{ format(calcBonus($package->points, $package->bonus_percentage)) }}
                                    </span>
                                @endif
                            </td>
                            <td class="text-right">{{ currencyFormat($package->price) }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4">
                                <div class="form-check">
                                    <input id="confirmation" name="confirmation" type="radio" required="required" class="form-check-input">
                                    <label for="confirmation" class="form-check-label"><small>I agree to terms of service</small></label>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>

            <div class="card-footer text-right">
                <button type="submit" class="btn btn-primary">
                    Checkout
                </button>
            </div>
        </form>
    </div>
@endsection

@section('scripts')
    <script>
        $('tr').on('click', function () {
            $(this).find('[type="radio"]').prop('checked', true);
        });
    </script>
@endsection

resources/views/orders/completed.blade.php
@extends('layouts.default')

@section('title', 'Order placed')

@section('content')
    <div class="card">
        <div class="card-header">
            @yield('title')
        </div>
        <div class="card-body">
            @if($order->status !== 'completed')
                Your order has been placed. but the payment was not yet received.<br>
                Please keep this page open. We will check your transaction every 30 seconds!
            @else
                Your order has been completed. and the points have been added to your account!<br>
                We thank you for your patronage!
            @endif
        </div>
    </div>
@endsection

@if($order->status !== 'completed')
    @section('scripts')
        <script>
            setInterval(function () {
                location.href = '{{ route('order.status') }}?tx={{ $order->transaction_id }}&item_number={{ $order->id }}';
            }, 30000);
        </script>
    @endsection
@endif

resources/views/orders/history.blade.php
@extends('layouts.default')

@section('title', 'Order history')

@section('content')
    <div class="card">
        <div class="card-header">
            @yield('title')
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Status</th>
                    <th class="text-right">Date</th>
                </tr>
                </thead>
                <tbody>
                @forelse($orders as $key => $order)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $order->package->name }}</td>
                        <td>{{ currencyFormat($order->package->price) }}</td>
                        <td>{{ $order->status }}</td>
                        <td class="text-right">{{ $order->package->created_at->format('Y-m-d') }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">No results...</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        @if($orders->count() > 10)
            <div class="card-footer">
                {{ $orders->links() }}
            </div>
        @endif
    </div>
@endsection

@section('styles')
    <style>
        .pagination {
            justify-content: center !important;
        }
    </style>
@endsection